### ISSUE TITLE
Duplicated maps in Statistics

### ISSUE THREAD

**Issue by marco93f** [w3champions/w3champions-ui#235]
https://www.w3champions.com/OverallStatistics
Under Played Maps, Select Season: All
- 1vs1: Last Refuge and mapNames.lastrefuge.anon
- 2vs2: 2x Phantm Grove W3C
- 2vs2: 2x Vile Reef

**Comment by Cepheid-UK** [comment]
mapNames.lastrefuge.anon requires a DB merge, Abeninski will have to deal with that.

**Comment by modmoto** [comment]
:)

**Comment by modmoto** [comment]
kk, should be fixed now. Do I close it, or do we have a new policy?

**Comment by modmoto** [comment]
kk, i close this one then ;)

**Comment by marco93f** [comment]
The issue is still in place:
- duplicated Autumn Leaves for "Select Mode" or "1vs1" mode and season "All";
- duplicated Vile Reef for "2vs2" mode and season "All".

**Comment by modmoto** [comment]
douh xD

**Comment by zygissss** [comment]
done

**Comment by MichaelDeitz** [comment]
Has this been fixed? I see @zygissss  said done but wanted to double check and see if we can get this closed.
